### ISSUE TITLE
DropWhenFull is a duplication glitch

### ISSUE THREAD

**Issue by Legit4K** [NoahBPeterson/AutoInv#3]
Can you set it to drop items on full inventory by default, and if you use haste hack // instant mine, the block doesn't break and the item goes into inventory, essentially its a duplication glitch

**Comment by NoahBPeterson** [comment]
Can you go into more detail about what "haste hack // instant mine" are? Are they plugins or enchantments? If they're plugins, can you link it here so I know what you're talking about?

**Comment by Legit4K** [comment]
Sorry, I mean instant mine hacks and haste effect hacks

**Comment by NoahBPeterson** [comment]
What plugin are those from? Can you give me a link?

**Comment by Legit4K** [comment]
They are not plugins, they are hacks, i.e MODS via blocklauncher

**Comment by Legit4K** [comment]
http://instinctmods.com

**Comment by Legit4K** [comment]
I'll record a video of it, if it helps

**Comment by NoahBPeterson** [comment]
Gotcha, I'll have an update out soon.

**Comment by Legit4K** [comment]
https://youtu.be/alvAJELOGR8

**Comment by NoahBPeterson** [comment]
A comment from the person that posted that says it's already been patched. Are you sure the issue is with AutoInv?

**Comment by Legit4K** [comment]
Deleted link for certain reasons

**Comment by NoahBPeterson** [comment]
Hah. Nice try. Thank you for letting me know that option wasn't working, creating a duplication glitch.

**Comment by Legit4K** [comment]
Yeah, will there be an update?

**Comment by NoahBPeterson** [comment]
Yeah, as soon as I fix the duplication bug.

**Comment by Legit4K** [comment]
Won't let me build into jar 🤔
Do you have a pre compiled one?

**Comment by NoahBPeterson** [comment]
https://nukkitx.com/resources/autoinventory.162/history

**Comment by Legit4K** [comment]
It still seems to duplicate regardless of if its set to true or false 🤔

**Comment by NoahBPeterson** [comment]
Try now.

**Comment by Legit4K** [comment]
Can you provide a jar for latest version?

**Comment by NoahBPeterson** [comment]
http://uppit.com/z6t4h5dl3pz4
